### ISSUE TITLE
[组件名称] 低版本node不支持

### ISSUE THREAD

**Issue by Jean-Jacques-Nuoan** [Tencent/tlbs-map-vue#10]
### tlbs-map-vue 版本

1.0.0

### 重现步骤

yarn install

### 期望结果

正常安装

### 实际结果

Output:
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:path'
Require stack:
- /workspace/iplus/test/address-reform/iplus-mobile/node_modules/tlbs-map-vue/scripts/postinstall.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object. (/workspace/iplus/test/address-reform/iplus-mobile/node_modules/tlbs-map-vue/scripts/postinstall.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspace/iplus/test/address-reform/iplus-mobile/node_modules/tlbs-map-vue/scripts/postinstall.js'
  ]
}
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

### 框架版本

Vue(2.7.16)

### Node版本

Node(14.16.0)

### 补充说明

postinstall脚本require('node:path')不支持，希望兼容低版本node写法,毕竟vue2的用户并不是都是用的node16以上版本

**Comment by Bright0810** [comment]
nvm 切换下node版本 不就可以了么

**Comment by Jean-Jacques-Nuoan** [comment]
> nvm 切换下node版本 不就可以了么

希望支持下，如果我能切换node版本就不会在这儿提issue了

**Comment by Bright0810** [comment]
我安装低版本也是安装不了 我是用nvm切换node到  22.11.0  npm install --save tlbs-map-vue --force  安装完 在用nmv 把node 切换到低版本 运行项目的
