### ISSUE TITLE
Vue 2.0版本无法使用地图

### ISSUE THREAD

**Issue by zkguanjia** [Tencent/tlbs-map-vue#2]
### tlbs-map-vue 版本

1.1.0

### 框架版本

Vue2.6.10

**Comment by zkguanjia** [comment]
提示错误如下：
internal/modules/cjs/loader.js:895
  throw err;
  ^

Error: Cannot find module 'node:path'
Require stack:
- /Users/apple/Desktop/光伏运维平台系统/源码/SaiBaoPVPage/node_modules/_tlbs-map-vue@1.1.0@tlbs-map-vue/scripts/postinstall.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/apple/Desktop/光伏运维平台系统/源码/SaiBaoPVPage/node_modules/_tlbs-map-vue@1.1.0@tlbs-map-vue/scripts/postinstall.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/apple/Desktop/光伏运维平台系统/源码/SaiBaoPVPage/node_modules/_tlbs-map-vue@1.1.0@tlbs-map-vue/scripts/postinstall.js'
  ]
}
[npminstall:runscript:error] tlbs-map-vue@latest scripts.postinstall run "node scripts/postinstall.js" error: Error [RunScriptError]: Run "sh -c node scripts/postinstall.js" error, exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:114:21)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12) {
  stdio: [Object],
  exitcode: 1
}
✖ Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "sh -c node scripts/postinstall.js" error, exit code 1

[npminstall:runscript:error] tlbs-map-vue@latest scripts.postinstall run "node scripts/postinstall.js" error: Error [RunScriptError]: Run "sh -c node scripts/postinstall.js" error, exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:114:21)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12) {
  stdio: [Object],
  exitcode: 1
}
✖ Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "sh -c node scripts/postinstall.js" error, exit code 1
RunScriptError: Run "sh -c node scripts/postinstall.js" error, exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:114:21)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
npminstall version: 5.8.1
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/Users/apple/.cnpmrc --disturl=https://npmmirror.com/mirrors/node --registry=https://registry.npmmirror.com tlbs-map-vue

**Comment by mimaster** [comment]
"node:path"是node 16以上版本才有的别名，你是node版本太低了
